apiVersion: v1
kind: Service
metadata:
  name: postgres-domen
  labels:
    component: postgres-domen
spec:
  type: LoadBalancer
  selector:
    component: postgres-domen
  ports:
  - name: http
    port: 5432
    protocol: TCP
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: postgres-domen
spec:
  selector:
    matchLabels:
      component: postgres-domen
  template:
    metadata:
      labels:
        component: postgres-domen
    spec:
      containers:
        - image: launcher.gcr.io/google/postgresql9
          name: postgres-domen
          env:
            - name: "POSTGRES_PASSWORD"
              value: "example-password"
          volumeMounts:
            - name: data-domen
              mountPath: /var/lib/postgresql/data
              subPath: data-domen
      volumes:
        - name: data-domen
          persistentVolumeClaim:
            claimName: data-domen
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-domen
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi