# Generated by Django 2.0.6 on 2018-07-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colonne',
            name='agr_age_maxi',
        ),
    ]
